- hosts: all
  remote_user: ubuntu
  become: yes
  
  tasks:
    - name: Adding Java Repo
      apt_repository:
        repo: ppa:openjdk-r/ppa
        
    - name: Install java
      apt:
        update_cache: yes
        name: openjdk-8-jdk
        state: latest
        install_recommends: no
      become: yes

    - name: Adding key 
      apt_key:
        url:  https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      become: yes

    - name: Adding Repo
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        filename: jenkins
        state: present
      become: yes

    - name: Installing jenkins  
      apt:
        update_cache: yes
        name: jenkins
        state: present
      become: yes

    - name: Viewing initial password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: pwd_jenkins
      become: yes
    - name: 
      debug:
        msg: "{{pwd_jenkins}}"

