- hosts: all
  remote_user: ubuntu
  
  tasks: 
  - name: Creating a Directory
    file:
      path: $HOME/Dir1
      state: directory
  
  - name: Create a file
    file: 
      path: "$HOME/Dir1/{{item}}"
      state: touch
    register: file_output
    with_items:
      file1.txt
      file2.txt
      file3.txt

